title = "config file"

[general]
usecudnn = true
usecudnnbenchmark = true
gpuid = 0
loadpretrainedmodel = true
pretrainedmodelpath = "model_save/densenet201100.pkl"

savemodel = true
model_save_directory_path = "model_save"


[input]
batchsize = 16
shuffle = true

[model]
type = "densenet201"
inputdim = 256
hiddendim = 256
numclasses = 311
numlstms = 2

[training]
train = true
start_epochs = 100
end_epochs = 150
startepoch = 0
statsfrequency = 1000
learningrate = 0.1
momentum = 0.9
weightdecay = 0.0001

[validation]
validate = true
saveaccuracy = true
accuracyfilelocation = "accuracy.txt"

[dataset]
add_train_dataset_absolute_path = true
train_dataset_absolute_path = "/home/z195/home/z195/datasets/crop_lips/lip_train"
test_dataset_absolute_path = "/home/maggi/dataset/lip/crop_lips/lip_test"
train_dataset_annotation_file_set = ""
train_test_dataset_annotation_file_set = ""
test_dataset_annotation_file_set = ""
map_index_hanzi_file_path = "data/label_table.csv"

[testing]
test_model = "testmodel.pkl"

[log]
logs_accuracy_path = "logs/accuracy.txt"
logs_train_path = "logs/train_log.txt"
logs_dir = "logs"